[project]
name = "drl-for-a-pathfinding-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    #"setuptools", 
    "numpy>=1.26,<2",
    "pandas",
    "networkx",
    "requests",
    "scipy",
    "littleballoffur@git+https://github.com/ellariel/littleballoffur",
    "torch",
    "torchvision",
    "torchaudio",
    "stable-baselines3[extra]",
    # "gymnasium",
    "tqdm",
    "seaborn",
    "ipykernel"
]
